### ISSUE TITLE
Esf Semantic Converter crashes when converting a saved game.

### ISSUE THREAD

**Issue by Ding-adong** [taw/etwng#11]
https://github.com/taw/etwng/blob/ee73eb19b4a4de705f092701d6fb96aeeb3e98f7/esfxml/esf_semantic_converter.rb#L1839

def convert_rec_COMMANDER__DETAILS (added another _)

No more crashes.

**Comment by taw** [comment]
Could you send me the crashing ESF?

**Comment by Ding-adong** [comment]
Don't have it anymore, sorry.

When you convert a saved game there is a warning saying commander-details not converted, 255 errors etc. This using cmd under windows 7. I have done some correction in esf_semantic_converter.rb <=! desc => as some description were incorrect. i will send that in by the end of the week when i have finish ok.

**Comment by Ding-adong** [comment]
Created a fork and uploaded esf_semantic_converter.rb. Can you check the file. Also look at line 1891.

**Comment by taw** [comment]
Merged all your changes.

**Comment by taw** [comment]
@Ding-adong Is there anything else or is it working for you after the merge?

**Comment by taw** [comment]
I'm going to take it as everything working. If you have any more issues, let me know (best with sample of failing file).
