### ISSUE TITLE
xml2esf errors

### ISSUE THREAD

**Issue by Ding-adong** [taw/etwng#12]
Uploaded a new esf_semantic_converter.rb and 4 error files in https://github.com/Ding-adong/etwng

When converting a save game from xml to esf, occasionally there are errors.

Looking at hex of the old and new files, 549e cb04 => TžË seems to be missing from the new file.

**Comment by Ding-adong** [comment]
Uploaded new esf_semantic_converter.rb and xml2esf and i do believe the errors no longer exist. However do check it for me.

**Comment by taw** [comment]
I merged version from your repo.

**Comment by Ding-adong** [comment]
Hang on there...

Last update for now. esf_semantic_converter.rb

I have uploaded NodesDescriptions.xml for esf editor and is this ok? The descriptions are the same as annotations in esf_semantic_converter and the game text pop up boxes. Downloaders can copy the NodesDescriptions.xml into their esf folder themselves.

cheers

**Comment by taw** [comment]
I've never heard of NodesDescriptions.xml , but I can include it if you want.

**Comment by Ding-adong** [comment]
thanks.
