### ISSUE TITLE
Error when trying to convert TW3K save files

### ISSUE THREAD

**Issue by burnce** [taw/etwng#13]
Hello,

I am receiving an "Unknwn Tyoe 0x26" error when opening files from TW 3 Kingdoms. This seems to an evolution of the file format.

Cheers,

Burnce

Traceback (most recent call last):
	20: from ./esf2xml:39:in `<main>'
	19: from /private/tmp/esfxml/etwng-master/esfxml/esf_converter.rb:416:in `convert!'
	18: from /private/tmp/esfxml/etwng-master/esfxml/dir_builder.rb:35:in `open_main_xml'
	17: from /private/tmp/esfxml/etwng-master/esfxml/dir_builder.rb:28:in `open_xml'
	16: from /private/tmp/esfxml/etwng-master/esfxml/esf_converter.rb:417:in `block in convert!'
	15: from /private/tmp/esfxml/etwng-master/esfxml/esf_converter.rb:440:in `tag!'
	14: from /private/tmp/esfxml/etwng-master/esfxml/dir_builder.rb:122:in `tag!'
	13: from /private/tmp/esfxml/etwng-master/esfxml/esf_converter.rb:419:in `block (2 levels) in convert!'
	12: from /private/tmp/esfxml/etwng-master/esfxml/esf_converter.rb:339:in `convert_abca_rec!'
	11: from /private/tmp/esfxml/etwng-master/esfxml/esf_converter.rb:323:in `convert_rec!'
	10: from /private/tmp/esfxml/etwng-master/esfxml/esf_converter.rb:305:in `convert_rec_basic!'
	 9: from /private/tmp/esfxml/etwng-master/esfxml/esf_converter.rb:440:in `tag!'
	 8: from /private/tmp/esfxml/etwng-master/esfxml/dir_builder.rb:122:in `tag!'
	 7: from /private/tmp/esfxml/etwng-master/esfxml/esf_converter.rb:311:in `block in convert_rec_basic!'
	 6: from /private/tmp/esfxml/etwng-master/esfxml/esf_converter.rb:341:in `convert_abca_rec!'
	 5: from /private/tmp/esfxml/etwng-master/esfxml/esf_converter.rb:323:in `convert_rec!'
	 4: from /private/tmp/esfxml/etwng-master/esfxml/esf_converter.rb:305:in `convert_rec_basic!'
	 3: from /private/tmp/esfxml/etwng-master/esfxml/esf_converter.rb:440:in `tag!'
	 2: from /private/tmp/esfxml/etwng-master/esfxml/dir_builder.rb:122:in `tag!'
	 1: from /private/tmp/esfxml/etwng-master/esfxml/esf_converter.rb:311:in `block in convert_rec_basic!'
/private/tmp/esfxml/etwng-master/esfxml/esf_converter.rb:286:in `block in setup_esf_type_handlers': Unknown type 0x26 at 58 (RuntimeError)

**Comment by taw** [comment]
Hi,

The converter needs update pretty much every time new game comes out. Just send me the save files and I'll update the converter.

**Comment by burnce** [comment]
Hello,

Thanks for the quick response. Here are two save files. Please let me know if you need more.
[tw3k_1.zip](https://github.com/taw/etwng/files/6101167/tw3k_1.zip)
[tw3k_2.zip](https://github.com/taw/etwng/files/6101168/tw3k_2.zip)

Thanks,

Burnce

**Comment by taw** [comment]
Try it now. I fixed a few issues, but there could be more.

**Comment by burnce** [comment]
Thanks for the quick fix. I have no errors anymore and can explore the output. I have managed to make a full loop of esf2xml --> xml2esf with no changes in between and load a game so I am assuming it is working.

There is a xz-compressed data file which can be decompressed and the nested esf is then also extractable. Is this usual for other games? The unpack_nested_esf does not seem to handle the compressed data. This may be due to a lack of appropriate libraries/tools on my system (I am on a Mac).

**Comment by taw** [comment]
You need to install lzma, homebrew should have it.
All saves since like Shogun 2 or Rome 2 (don't remember exactly) have this compressed second level inside, as Empire saves were enormous.

**Comment by burnce** [comment]
Thanks for the tip. I finally got things to work on a mac. A few issues with the code, but mainly the lzma version is important.

- Legacy lzma tools from https://tukaani.org/lzma/ work for compression
- More recent xz based implementations create a different compressed file format which gets corrupted when integrated into an esf (roundtrip-with-no-changes success mentioned in my previous message was in fact incorrect as compression of new `compressed_data.esf` was being skipped by pack_nested_esf).
- For decompression, lzma tools refuse to work on .xz extension and even with file renaming, things get tedious since multiple renames are needed.

I'll explore a bit further and prepare a pull request when I get things to work.

**Comment by taw** [comment]
Yeah, I've noticed that the Windows lzma binary I bundled works, but the newer one had similar issues to what you mentioned.

I suspect we could get new ones to work by just changing command line switches, but I think it's best to just bundle lzma for a bunch of OSes, if it's just one file for each.

**Comment by burnce** [comment]
Pull request submitted
#14 
I have tested on mac only (ruby and jruby)
I did not bundle lzma since my build links to dynamic libraries, but rather added support for pointing to specific lzma executables.

**Comment by burnce** [comment]
Just a quick ping to let you know that I have updated the pull-request

**Comment by taw** [comment]
Is everything working as expected now, or are there any further issues with TW3K?

**Comment by burnce** [comment]
It is working, thanks

**Comment by taw** [comment]
Closing the issue if it works.
