### ISSUE TITLE
These scripts are very hard to use for beginners

### ISSUE THREAD

**Issue by trevor403** [taw/etwng#2]
I am a skilled coder but I can not understand how to run your scripts. I assume that you want them to be  usable to unskilled people because you write nice readme's for your major tools. But even getting jruby setup is hard for a beginner. I suggest you expand the readme's for each tool to be more specific and include prerequisites and the current working directory of each example command. Also to add a setup guide to the main readme.

**Comment by taw** [comment]
JRuby should be easy to setup, just grab it from http://jruby.org/download
use default setting (and possibly reboot your computer just in case, even
though that's probably not required)

Generally the scripts don't require any special current working directory,
they just take input path as first argument and output path as second
argument, some kind of:

jruby unpack_xxx file.xxx file.txt

Some people even wrote GUI frontends for some of them (esf - xml
conversions), but I never used any of them.

What are you trying to accomplish? The forums are good place for tech
support, there's plenty of people who've been successful with that :-)

**Comment by trevor403** [comment]
Rigid model conversion, I'm taking models from R2TW and I needed something more automated (scripting) than a UI like Ultimate Unwrap3D

**Comment by taw** [comment]
.rigid_model_v2? I don't have anything for that, the code literally says
"THIS IS JUST EXPERIMENTAL CODE, IT DECODES NOTHING" on top of the file as
that was just investigation hack, not actual decoder :-)

**Comment by trevor403** [comment]
Yes I saw that folder but there is also some code in the etwconv folder I
thought could be useful?

**Comment by taw** [comment]
Everything in etwconv is also random experiments from Empire Total War
days, most stuff from there that got finished got its own converters in its
own directories.

I could definitely do better job at separating actually working converters
from experimental unfinished code. :-/

**Comment by taw** [comment]
Generally formats where another converter already exists (like Ultimate
Unwrap3D) I see as lower priority, and they often didn't get proper
converters written.

On 21 June 2015 at 21:45, Tomasz Wegrzanowski <tomasz.wegrzanowski@gmail.com
> wrote:

> Everything in etwconv is also random experiments from Empire Total War
> days, most stuff from there that got finished got its own converters in its
> own directories.
>
> I could definitely do better job at separating actually working converters
> from experimental unfinished code. :-/
>

**Comment by taw** [comment]
I can't say it got any easier, but closing old issues. If people still have trouble, I might take a look at some updated instructions for installing jruby.
