### ISSUE TITLE
Does this work for later Total War titles and how to use

### ISSUE THREAD

**Issue by gdwitt** [taw/etwng#21]
I am looking for a weak to read startpos for Attila TW. I found this through google, but it doesn't appear to explain itself well:
1) Has it been tested with Attila/Rome2? 
2) How to set it up? I see it is written in Ruby so what is needed to run it?

**Comment by taw** [comment]
Depends on which converter you need. A lot of them like the one for startpos work on all the games from ETW up to WH2 (I haven't tested them on WH3 yet, but they might), but some are only for a few games.

[Yes, you'll need to to install Ruby](https://rubyinstaller.org/).

**Comment by gdwitt** [comment]
Great. Does it matter which version of Ruby I use? Are there directions on how to link the installation to the tool?

**Comment by taw** [comment]
Just pick latest, any version is fine unless it's extremely old

**Comment by gdwitt** [comment]
I am trying to get the ESF to XML converter to work. I found the INstall.txt and followed the instructions: 1) Install JRuby  2) Install_noko giri 3) Run Izma somehow. I did 1 and 3 by just double clicking the files. I saw a flash cmd line that disappeared for each. I still can't open an application here. Please provide clear instructions. This could be revolutionary if it works.

**Comment by gdwitt** [comment]
Bump. Still interested. Do you have a guide somewhere or Readme to explain this to the tw audience. You have a high profile reference here: https://www.twcenter.net/forums/showthread.php?707386-Using-ESFviaXML-to-Unpack-Startpos-and-Save-Games-into-Text-Files&highlight=startpos

**Comment by taw** [comment]
They are all command line tools, so it would be difficult to use unless you're familiar with command line.

I know there are some friendly UI tools that my converters, but I'm not really following that.

**Comment by taw** [comment]
By the way if anyone wants to write some guides, just PR it, and I'll add to to the README.

**Comment by M-Mulder** [comment]
> By the way if anyone wants to write some guides, just PR it, and I'll add to to the README.

Sure i will write some guides!

**Comment by taw** [comment]
@gdwitt  @M-Mulder Any interest in this issue, or should I close it?

**Comment by gdwitt** [comment]
If no good guide or GUI is available, we might as well close it.  Breaking out startpos would still be a valuable tool.

**Comment by taw** [comment]
OK, closing it.
