### ISSUE TITLE
[ESFXML] XML Error: EntityRef: expecting ';'

### ISSUE THREAD

**Issue by M-Mulder** [taw/etwng#24]
<img width="716" alt="idea64_YzXUeMrLnL" src="https://github.com/taw/etwng/assets/91462401/bbfb4a95-b64f-41ab-8418-f95844b0bf80">

I am trying to change data in the compressed_data.esf section within a Total War Attilla save file. 
So first I unpack it without issues, however after trying to pack it again with xml2esf I get this error:

`PS C:\Users\Defcon\Downloads\etwng-master\esfxml\mp> cd ..`
`PS C:\Users\Defcon\Downloads\etwng-master\esfxml> ruby esf2xml compressed_data.esf compressed_data`
`PS C:\Users\Defcon\Downloads\etwng-master\esfxml> ruby xml2esf compressed_data compressed_data.esf`
`XML Error: EntityRef: expecting ';'`
`XML Error: EntityRef: expecting ';'`

After this it will export a file, **but this file is broken/incomplete**

### **I tried the same thing with linux, but it gives the same issue.**

For reference this is the savefile I'm trying change, if that may be of use:

[MUL.zip](https://github.com/taw/etwng/files/12261609/MUL.zip)

**Comment by M-Mulder** [comment]
PS: im trying to convert the save game from multiplayer to singleplayer. Not sure if its bugging out because its a multiplayer file, but i thought it was worth mentioning @taw Thanks for your work, and hope for a response

**Comment by taw** [comment]
OK, [so I have fix for the XML issue](https://github.com/taw/etwng/commit/7133d5f457bb200ab3dd2f4eed835e81b44bed7c), but I'm seeing some unrelated issue with `<i4_ary>` decoding in this file, so I'll need to fix it, or you risk getting bad data there.

**Comment by taw** [comment]
[OK, the other issue fixed as well](https://github.com/taw/etwng/commit/0be7c008548b03cc8d4f5617fa367f44c1f4508a), it should all work now.

**Comment by M-Mulder** [comment]
PS C:\Users\Defcon\Downloads\etwng-master (2)\etwng-master\esfxml> ruby xml2esf compressed_data compressed_data.esf
xml2esf:1478:in `parse_file': No such file or directory: compressed_data/domestic_trade_routes/0119.xml (RuntimeError)
        from xml2esf:1104:in `on_empty_node_xml_include'
        from xml2esf:1447:in `end_element_namespace'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.3-x64-mingw-ucrt/lib/nokogiri/xml/sax/parser.rb:106:in `parse_with'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.3-x64-mingw-ucrt/lib/nokogiri/xml/sax/parser.rb:106:in `parse_file'
        from xml2esf:1479:in `parse_file'
        from xml2esf:1104:in `on_empty_node_xml_include'
        from xml2esf:1447:in `end_element_namespace'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.3-x64-mingw-ucrt/lib/nokogiri/xml/sax/parser.rb:106:in `parse_with'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.3-x64-mingw-ucrt/lib/nokogiri/xml/sax/parser.rb:106:in `parse_file'
        from xml2esf:1479:in `parse_file'
        from xml2esf:1104:in `on_empty_node_xml_include'
        from xml2esf:1447:in `end_element_namespace'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.3-x64-mingw-ucrt/lib/nokogiri/xml/sax/parser.rb:106:in `parse_with'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.3-x64-mingw-ucrt/lib/nokogiri/xml/sax/parser.rb:106:in `parse_file'
        from xml2esf:1479:in `parse_file'
        from xml2esf:1104:in `on_empty_node_xml_include'
        from xml2esf:1447:in `end_element_namespace'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.3-x64-mingw-ucrt/lib/nokogiri/xml/sax/parser.rb:106:in `parse_with'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.3-x64-mingw-ucrt/lib/nokogiri/xml/sax/parser.rb:106:in `parse_file'
        from xml2esf:1479:in `parse_file'
        from xml2esf:1487:in `initialize'
        from xml2esf:1472:in `new'
        from xml2esf:1472:in `parse'
        from xml2esf:1505:in `<main>'

### 
**Now im getting this error**

**Comment by taw** [comment]
I'm not sure what's going on there, it says some files are missing. Did you move some files around or modify them in a weird way?

It works for me just fine after these fixes.

**Comment by M-Mulder** [comment]
No im just copying and pasting CAMPAIGN_ENV to another savefile, and then packing it. manually generating 0119.xml worked, but the save game wont load. Such a shame its so difficult to convert a multiplayer game to a singleplayer game.

**Comment by taw** [comment]
The converter just turns esf into xml and back, it doesn't know anything about what needs to be done to convert a multiplayer save to a singleplayer save.

**Comment by M-Mulder** [comment]
I'm aware of that, just cursing to myself lol
