### ISSUE TITLE
TWW3 start_pos.esf error

### ISSUE THREAD

**Issue by De1endaest** [taw/etwng#26]
I got an error while trying to convert TWW3's start_pos.esf to xml. I don't know enough about this kind of software to try to troubleshoot what's going on. 
Command & message log:
https://pastebin.com/qkczXmGJ
Failing file:
[startpos.zip](https://github.com/user-attachments/files/17019751/startpos.zip)

**Comment by taw** [comment]
OK, I did two Warhammer 3 fixes, I think it should work now.

Let me know if you get any other crashes, new games sometimes change something.

**Comment by taw** [comment]
@De1endaest Did it work?

**Comment by De1endaest** [comment]
It did. Sorry for not responding sooner.
