### ISSUE TITLE
Problems with FotS startpos

### ISSUE THREAD

**Issue by Primergy** [taw/etwng#3]
Hey, I wanted to convert the "Fall of the Samurai" startpos, but it only gives me 3 folders out. 
The conversion works with Shogun2 startpos, so i assume there were version changes. 

What I wanted to try was to get an entry from the "Rise of the Samurai", specifically the "unit_names_allocator" and paste it to the FotS Startpos to see if can enable regiment names like in etw.

**Comment by taw** [comment]
Isn't FotS when they started compressing `startos.esf`?

You need (de)compression program `lzma.exe`, which is conveniently even included here.

`unpack_nested_esf` and `pack_nested_esf` scripts conveniently do it all (unpack, uncompress, unpack second time, and the reverse) in one command.

**Comment by Primergy** [comment]
Ah, didn't know that they are compressed now. But conversion works now. Thanks!

But now I run into another problem. I wanted to extract the "HERO_UNIT_NAME_ALLOCATOR" entries with xml_split and entered following code (:HERO_UNIT_NAME_ALLOCATOR  => HERO_UNIT_NAME_ALLOCATOR/",) but it doesn't work.

**Comment by taw** [comment]
`:HERO_UNIT_NAME_ALLOCATOR => "HERO_UNIT_NAME_ALLOCATOR/",` should work.

In which way it doesn't work? Crashes, or just doesn't split that?

**Comment by Primergy** [comment]
It doesn't split that specific part

**Comment by taw** [comment]
Did you try maybe splitting one level higher or something like that, if that's good enough? If not, just drop that file somewhere, and I'll take a look at it.

**Comment by Primergy** [comment]
One level higher (and deeper) didn't worked either.
here you can find the RotS startpos, would be great if you could take a quick look at it.
https://www.dropbox.com/s/o989ylr9hhfnhs1/startpos.esf?dl=0

**Comment by taw** [comment]
I fixed some Ruby 2.x compatibility problems (it was crashing on me in one of data structures introduced in S2 DLC time).

And I included `HERO_UNIT_NAME_ALLOCATOR` line in the code, and I'm getting it just fine in the output.

**Comment by Primergy** [comment]
Well, atleast we know that the error is on my side, though I don't see what I'm doing wrong. 

Might it be possible that you send me unpacked startpos as zip?

**Comment by taw** [comment]
Here it is https://www.dropbox.com/s/zqb9mvls1dzwm7c/unpacked_startpos.7z?dl=0

**Comment by taw** [comment]
Closing as presumably solved by now.
