### ISSUE TITLE
New issue? ToB

### ISSUE THREAD

**Issue by Tomfow** [taw/etwng#8]
Hi, I was happily packing new altered startpos when i got lower problem:
https://i.ibb.co/JHX4hCp/powershell.png
Yesterday i packed successfully another startpos, so maybe i messed something in editing XML tables..
I zipped the unpacked altered startpos 
https://drive.google.com/open?id=1H_KGEEwz80gPgmM4HClTzSg4VI8J0FPZ

**Comment by Tomfow** [comment]
hmmm tried to unpack/pack original startpos without any changes and it went well..i will try to replicate my changes once again. Maybe im just dumb..

**Comment by Tomfow** [comment]
ok, no idea what went wrong, manual recreation of all changes went right this time. So no more issue...Startpos is packed.

Anyway thanks once more for awesome tool! :)

**Comment by taw** [comment]
I'm glad it worked out fine then :-D
