### ISSUE TITLE
Decompile scripts partially...

### ISSUE THREAD

**Issue by The-Meth0d** [taw/etwng#9]
Hi, great work on this decompiler!

I was able to succesfully decompile some scripts 100%, but there are some others scripts (from the same game) that decompile partially and gives me only 40%, 60% of the script...

The error ArrayOutOfIndexBounds shows up.

 What may be wrong ?

**Comment by taw** [comment]
What's wrong is that version of lua decompiler targets is older than version of lua game actually uses so that's unfortunately expected.

Last time I checked there were no lua decompilers for the right version, but that was very long time ago, so maybe someone wrote one?

**Comment by LeoMeth0d** [comment]
The game script i'm using is from Jakcass 2007, it's version is 50...

I also tried to use luadec but it gives me this error: **size of number is 8 but read 4**
Any chance that this is a 64bit decompile problem?

**Comment by taw** [comment]
You definitely need to build 32bit version of decompiler. lua is not like java where .jar is a jar.
lua files compiled on one system will not run on system with different byte size.

Total War lua uses 32 bit ints and 32 bit floats (lua default is 32 / 64 or 64 / 64 depending on your system).

Build script from this repo sets correct flags, but I'm not sure if it still works on 64bit system.

**Comment by LeoMeth0d** [comment]
Ok, thanks for the support man, i'll see what I can get!

**Comment by taw** [comment]
So according to twcenter, best decompiler is to use this website - http://www.decompiler.com/

As far as I can tell it works a lot better than what I have here, and I updated README to point there, so I'll just close this issue.
